# Apache configuration for the Rufus for Linux homepage
<VirtualHost *:80>
Define RufusRoot /var/www/html
DocumentRoot ${RufusRoot}
Options Indexes MultiViews FollowSymLinks
IndexOptions FancyIndexing IconHeight=32 IconWidth=32 SuppressColumnSorting IconsAreLinks NameWidth=26 FoldersFirst IgnoreClient
Alias /icons ${RufusRoot}/icons
AddIcon /icons/back.png ..
AddIcon /icons/blank.png ^^BLANKICON^^
AddIcon /icons/rufus.png .deb
AddIcon /icons/compressed.png .tar.gz .gz
AddIcon /icons/binary.png
DefaultIcon /icons/binary.png
AddType application/x-debian-package .deb
AddType application/gzip .tar.gz
AddType application/octet-stream .po .mo .pot
DirectoryIndex index.php
IndexIgnore *.html *.sig
AddDescription "Rufus for Linux source tarball" rufusforlinux-*.tar.gz
AddDescription "Rufus for Linux Debian package" rufusforlinux-*.deb
</VirtualHost>
